### ISSUE TITLE
Mysterious babel error

### ISSUE THREAD

**Issue by jbaumbach** [glenjamin/ultimate-hot-reloading-example#14] opened 2016-02-17 23:27 UTC
After fresh clone and npm install just now, npm start gives this:

$ npm start

> ultimate-hot-reloading-example@1.0.0 start /Users/me/Documents/projects/react/ultimate-hot-reloading-example
> node server.js

Listening at http://127.0.0.1:3000
webpack built 11927603e83a7e38296a in 1824ms
Clearing /client/ module cache from server
Error: Cannot find module 'babel-runtime/core-js/json/stringify'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/me/Documents/projects/react/ultimate-hot-reloading-example/client/server-render.js:3:18)
    at Module._compile (module.js:434:26)
    at loader (/Users/me/Documents/projects/react/ultimate-hot-reloading-example/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js](/Users/me/Documents/projects/react/ultimate-hot-reloading-example/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

I can't find any reference to that in the code.

Any ideas?

**Comment by glenjamin** [comment] 2016-02-18 08:17
Babel runtime is pulled in by the transform here: https://github.com/glenjamin/ultimate-hot-reloading-example/blob/master/.babelrc

If you remove that like, you'll sidestep the error. I'll see if I can find what is causing it

**Comment by glenjamin** [comment] 2016-02-18 20:06
I just tried to reproduce, and i'm not seeing the error unfortunately

**Comment by carlosmontes** [comment] 2016-02-19 00:26
@glenjamin It looks like babel-runtime is missing from the package.json. @jbaumbach npm i --save-dev babel-runtime should get you up and running!

**Comment by jbaumbach** [comment] 2016-02-19 00:37
Crap, didn't even think about that.  Just presumed something else was broken like every other React framework older than 4 days.  Thanks!

**Comment by glenjamin** [comment] 2016-02-19 07:37
Aha, I'm on npm3 so didn't see this!

**Comment by glenjamin** [comment] 2016-02-19 08:33
Fixed in 8a3cca7

**Closed as completed by glenjamin** 2016-02-19 08:33 UTC
